import Head from 'next/head'
import { Layout } from 'antd'
import { ReactNode } from 'react'
import LayoutHeader from '@/components/Header'
import { TheFooter } from '@/components/Footer/Footer'

type Props = {
    title?: string
    children: ReactNode
}

export default function DefaultLayout(props: Props) {
    const { children, title } = props

    return (
        <>
            <Head>
                <title>{title || "Carrectly Auto Care"}</title>

                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <meta
                    name='title'
                    content=' description: Created by Carrectly Auto Care'
                />
                <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
                <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
                <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
                <link rel='icon' href='/favicon.ico' />
                <link rel="manifest" href="/site.webmanifest" />
                <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
                <meta name="msapplication-TileColor" content="#ffc40d" />
                <meta name="theme-color" content="#ffffff" />
            </Head>
            <Layout className='home-page page-gradient-bg'>
                <LayoutHeader />
                {children}
                <TheFooter />
            </Layout>
        </>
    )
}
