'use client'

import { useMediaQuery } from '@/hooks/useMediaQuery'
import ReqFreeConsult from '@/components/ReqFreeConsult'
import global from '@/styles/global.module.css'
import styles from './styles.module.css'
import Image from 'next/image'
import Head from 'next/head'
import LayoutHeader from '@/components/Header'
import { TheFooter } from '@/components/Footer/Footer'
import { Reviews, Whyus } from '@/components/Sections'
import { QUOTE_PAGE_FEATURES_LIST } from '@/components/Sections/WhyUs/constants'
import { MAIN_PAGE_REVIEWS } from '@/components/Sections/Reviews/contants'

const QuotePortalPage = () => {
    const isTabletOrMobile = useMediaQuery(960)

    return (
        <div className={global.body}>
            <div className={global.main}>
                <Head>
                    <title>Carrectly Quote Portal</title>

                    <meta
                        name='description'
                        content='Generated by create next app'
                    />
                    <meta
                        name='viewport'
                        content='width=device-width, initial-scale=1'
                    />
                    <meta
                        name='title'
                        content=' description: Created by Carrectly Auto Care'
                    />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <LayoutHeader />
                <section className={`${global.section} ${styles.heroBlock}`}>
                    <h1>Quote Portal</h1>
                    <span>
                        Created by enthusiasts for enthusiasts. We provide
                        automotive services for all cars to those looking for
                        the best. Delivering peace of mind and great support
                    </span>
                    <button
                        className={`${global.btn} ${global.btn__secondary}`}
                    >
                        Book now
                    </button>
                    <div>
                        <Image
                            src='/assets/images/icons/premium-quality.svg'
                            width={90}
                            height={80}
                            alt='Trust & Safety'
                        />
                        <Image
                            src='/assets/images/icons/best-customer-service.svg'
                            width={80}
                            height={80}
                            alt='Trust & Safety'
                        />
                        <Image
                            src='/assets/images/icons/best-products.svg'
                            width={73}
                            height={80}
                            alt='Trust & Safety'
                        />
                    </div>
                </section>
                <div className='container-xl container'>
                    <Whyus featuresListItems={QUOTE_PAGE_FEATURES_LIST} />
                </div>
                <section className={global.section}>
                    <h2>Request free consultation</h2>
                    <ReqFreeConsult />
                </section>
                <div className='container-xl container'>
                    <Reviews reviewsList={MAIN_PAGE_REVIEWS} />
                </div>
            </div>
            <TheFooter />
        </div>
    )
}

export default QuotePortalPage
