import { useMediaQuery } from '@/hooks/useMediaQuery'
import Image from 'next/image'
import MySlider from '@/components/MySlider'
import BookingForm from '@/components/BookingForm'
import Accordion from '@/components/Accordion'
import global from '@/styles/global.module.css'
import styles from './styles.module.css'
import faqData from '@/data/faqData'
import Head from 'next/head'
import LayoutHeader from '@/components/Header'
import TheFooter from '@/components/Footer/Footer'
import RelatedServices from '@/components/RelatedServices/RelatedServices'
import React from 'react'
import GooglePlacesScript from '@/utils/lib/googlePlacesScript'
import { Questions } from '@/components/Sections'

const advantagesData = [
    {
        image: (
            <Image
                src='/assets/images/icons/hassle-free.svg'
                width={87}
                height={72}
                alt='Hassle Free'
            />
        ),
        text: `Any auto service in one place on your time and on your schedule`,
    },
    {
        image: (
            <Image
                src='/assets/images/icons/no-obligations.svg'
                width={87}
                height={73}
                alt='No obligations'
            />
        ),
        text: `Сancel or reschedule anytime`,
    },
    {
        image: (
            <Image
                src='/assets/images/icons/pay-after.svg'
                width={80}
                height={71}
                alt='Pay After'
            />
        ),
        text: `No worries, pay only after services are completed`,
    },
    {
        image: (
            <Image
                src='/assets/images/icons/ready-to-support-you.svg'
                width={75}
                height={75}
                alt='Ready to support you'
            />
        ),
        text: `Text, Call, Email us with any questions`,
    },
]

const BookingPortalPage = () => {
    const isTabletOrMobile = useMediaQuery(960)

    const settings = {
        arrows: false,
        responsive: [
            {
                breakpoint: 600,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2,
                },
            },
            {
                breakpoint: 480,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                },
            },
        ],
    }

    return (
        <div className={global.body}>
            <div className={global.main}>
                <Head>
                    <title>Carrectly Booking Portal</title>

                    <meta
                        name='description'
                        content='Generated by create next app'
                    />
                    <meta
                        name='viewport'
                        content='width=device-width, initial-scale=1'
                    />
                    <meta
                        name='title'
                        content=' description: Created by Carrectly Auto Care'
                    />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <LayoutHeader />
                <section className={`${global.section} ${styles.heroBlock}`}>
                    <h1>Booking Portal</h1>
                    <div>
                        {!isTabletOrMobile ? (
                            <div className={styles.advantagesList}>
                                {advantagesData
                                    ? advantagesData?.map((item, index) => (
                                          <div
                                              key={index}
                                              className={styles.advantage}
                                          >
                                              {item.image}
                                              <span>{item.text}</span>
                                          </div>
                                      ))
                                    : ''}
                            </div>
                        ) : (
                            <div className={styles.advantagesSlider}>
                                <MySlider settings={settings}>
                                    {advantagesData
                                        ? advantagesData?.map((item, index) => (
                                              <div
                                                  key={`test-${index}`}
                                                  className={styles.advantage}
                                              >
                                                  <div>
                                                      {item.image}
                                                      <span>{item.text}</span>
                                                  </div>
                                              </div>
                                          ))
                                        : ''}
                                </MySlider>
                            </div>
                        )}
                    </div>
                </section>
                <section
                    className={`${global.section} ${styles.bookingFormWrapper}`}
                >
                    <div>
                        <BookingForm />
                        <div className={styles.bgElement}></div>
                    </div>
                </section>
                {!isTabletOrMobile && (
                    <section
                        className={`${global.section} ${styles.otherServicesBlock}`}
                    >
                        <RelatedServices />
                    </section>
                )}
                <section className={`${global.section}`}>
                    <Questions />
                </section>
            </div>
            <TheFooter />
            <GooglePlacesScript />
        </div>
    )
}

export default BookingPortalPage
